### ISSUE TITLE
Not including the compiler

### ISSUE THREAD

**Issue by PiotrGrochowski** [bingmann/sound-of-sorting#10]
Please include a converter for all these files to exe, which can be run on Windows.

**Comment by Thymo-** [comment]
![image](https://user-images.githubusercontent.com/7950685/34672266-1c059556-f47e-11e7-9f8d-0b5a0fe55ebb.png)

**Comment by PiotrGrochowski** [comment]
Then how the heck can you compile it on Wisonfdownsa>!>RNuI@y8s@ker3.uH*@!>>!>/?/!?#X!@?#????#RC?#?$R////????????????

**Comment by chromi** [comment]
A Windows executable is linked from here: http://panthema.net/2013/sound-of-sorting/

**Comment by PiotrGrochowski** [comment]
I'm lost at "use that". How do you do that?

**Comment by PiotrGrochowski** [comment]
Case closed, a compiler cannot do it.

    fatal error: wx/wx.h: No such file or directory

The source is missing the wx folder entirely.

**Comment by PiotrGrochowski** [comment]
fatal error: SDL.h: No such file or directory

The source is also missing SDL.h. Come on, what's the point of referencing non-existent files?

**Comment by chromi** [comment]
You really have no idea how a compiler works, do you?

Both of these headers are provided by external libraries, wxWindows and SDL respectively, which you need to install in such a way that the headers become visible to the compiler in its system search path.  I believe MinGW has a straighforward way to do that.

None of this is any fault of sound-of-sorting.

**Comment by PiotrGrochowski** [comment]
$ g++ WMain.cpp $(C:/wx/wx-config --libs) $(C:/wx/wx-config --cxxflags) -lSDL2main -lSDL2 -o test.exe
In file included from c:/wxWidgets-3.1.0/include/wx/intl.h:17,
                 from c:/wxWidgets-3.1.0/include/wx/wx.h:22,
                 from WMain.h:26,
                 from WMain.cpp:23:
WMain.cpp: In constructor 'WMain::WMain(wxWindow*)':
WMain.cpp:46:40: error: expected ')' before 'PACKAGE_VERSION'
     SetTitle(_("The Sound of Sorting " PACKAGE_VERSION " - http://panthema.net/2013/sound-of-sorting"));
                                        ^~~~~~~~~~~~~~~
c:/wxWidgets-3.1.0/include/wx/translation.h:38:56: note: in definition of macro '_'
     #define _(s)                     wxGetTranslation((s))
                                                        ^
c:/wxWidgets-3.1.0/include/wx/translation.h:38:55: note: to match this '('
     #define _(s)                     wxGetTranslation((s))
                                                       ^
WMain.cpp:46:14: note: in expansion of macro '_'
     SetTitle(_("The Sound of Sorting " PACKAGE_VERSION " - http://panthema.net/2013/sound-of-sorting"));
              ^
WMain.cpp:46:104: error: expected ')' before ';' token
     SetTitle(_("The Sound of Sorting " PACKAGE_VERSION " - http://panthema.net/2013/sound-of-sorting"));
                                                                                                        ^
                                                                                                        )
In file included from c:/wxWidgets-3.1.0/include/wx/intl.h:17,
                 from c:/wxWidgets-3.1.0/include/wx/wx.h:22,
                 from WMain.h:26,
                 from WMain.cpp:23:
c:/wxWidgets-3.1.0/include/wx/translation.h:38:54: note: to match this '('
     #define _(s)                     wxGetTranslation((s))
                                                      ^
WMain.cpp:46:14: note: in expansion of macro '_'
     SetTitle(_("The Sound of Sorting " PACKAGE_VERSION " - http://panthema.net/2013/sound-of-sorting"));
              ^
WMain.cpp: In constructor 'WAbout::WAbout(wxWindow*)':
WMain.cpp:293:56: error: expected ')' before 'PACKAGE_VERSION'
         labelTitle->SetLabel(_("The Sound of Sorting " PACKAGE_VERSION));
                                                        ^~~~~~~~~~~~~~~
c:/wxWidgets-3.1.0/include/wx/translation.h:38:56: note: in definition of macro '_'
     #define _(s)                     wxGetTranslation((s))
                                                        ^
c:/wxWidgets-3.1.0/include/wx/translation.h:38:55: note: to match this '('
     #define _(s)                     wxGetTranslation((s))
                                                       ^
WMain.cpp:293:30: note: in expansion of macro '_'
         labelTitle->SetLabel(_("The Sound of Sorting " PACKAGE_VERSION));
                              ^
WMain.cpp:293:73: error: expected ')' before ';' token
         labelTitle->SetLabel(_("The Sound of Sorting " PACKAGE_VERSION));
                                                                         ^
                                                                         )
In file included from c:/wxWidgets-3.1.0/include/wx/intl.h:17,
                 from c:/wxWidgets-3.1.0/include/wx/wx.h:22,
                 from WMain.h:26,
                 from WMain.cpp:23:
c:/wxWidgets-3.1.0/include/wx/translation.h:38:54: note: to match this '('
     #define _(s)                     wxGetTranslation((s))
                                                      ^
WMain.cpp:293:30: note: in expansion of macro '_'
         labelTitle->SetLabel(_("The Sound of Sorting " PACKAGE_VERSION));

$ g++ wxClickText.cpp $(C:/wx/wx-config --libs) $(C:/wx/wx-config --cxxflags) -lSDL2main -lSDL2 -o test.exe
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_mswu_xrc-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_mswu_html-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_mswu_qa-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_mswu_adv-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_mswu_core-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_baseu_xml-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_baseu_net-3.1
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lwx_baseu-3.1
collect2.exe: error: ld returned 1 exit status

This doesn't make sense. No Microsoft Windows executables were made.

**Comment by PiotrGrochowski** [comment]
Oops, Markdown formatting errors, Markdown is not a plaintext format.

**Comment by PiotrGrochowski** [comment]
Not to mention, the file has #include <SDL.h> when it seems like the proper syntax is #include <SDL2/SDL.h>. What's this?

**Comment by bingmann** [comment]
This is getting out of hand. While amusing at first, you really should learn how programming works.
But not by making nonsensical issues on this project.
